// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzxkGcZCZJjJfIFlZSpHXNiODa45C30Sc',
    appId: '1:670383568794:web:1db800ccceb906a8d06c23',
    messagingSenderId: '670383568794',
    projectId: 'todo-662e2',
    authDomain: 'todo-662e2.firebaseapp.com',
    storageBucket: 'todo-662e2.appspot.com',
    measurementId: 'G-BHNMYSCEME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi4LCdMuGV3n76XTxm1VLNSfB9QcIsgtE',
    appId: '1:670383568794:android:db951bb7b118e185d06c23',
    messagingSenderId: '670383568794',
    projectId: 'todo-662e2',
    storageBucket: 'todo-662e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB840unZkg8iPFIoScsI-9N4uvBIVUdC7E',
    appId: '1:670383568794:ios:e7727d26a4e275b4d06c23',
    messagingSenderId: '670383568794',
    projectId: 'todo-662e2',
    storageBucket: 'todo-662e2.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB840unZkg8iPFIoScsI-9N4uvBIVUdC7E',
    appId: '1:670383568794:ios:e7727d26a4e275b4d06c23',
    messagingSenderId: '670383568794',
    projectId: 'todo-662e2',
    storageBucket: 'todo-662e2.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzxkGcZCZJjJfIFlZSpHXNiODa45C30Sc',
    appId: '1:670383568794:web:f1b590a90e993896d06c23',
    messagingSenderId: '670383568794',
    projectId: 'todo-662e2',
    authDomain: 'todo-662e2.firebaseapp.com',
    storageBucket: 'todo-662e2.appspot.com',
    measurementId: 'G-NDFHCBGGMH',
  );

}